# Generated by Django 4.2.7 on 2026-04-08 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='payment_mode',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='ExpenseAdvanceAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_used', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('advance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_allocations', to='finance.advance')),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advance_allocations', to='finance.expense')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='expenseadvanceallocation',
            constraint=models.UniqueConstraint(fields=('expense', 'advance'), name='finance_expense_allocation_unique_expense_advance'),
        ),
    ]
