# Generated by Django 4.2.7 on 2026-04-08 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_experience_employee_alter_experience_candidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='role',
            field=models.CharField(choices=[('hr', 'HR'), ('checker', 'Checker'), ('employee', 'Employee'), ('admin', 'Admin'), ('management', 'Management')], default='employee', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('hr', 'HR'), ('checker', 'Checker'), ('employee', 'Employee'), ('admin', 'Admin'), ('management', 'Management')], default='employee', max_length=20),
        ),
    ]
